#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul 30 09:01:40 2019

@author: chandanav
"""
from JobShopLoader import *

jobshopLoader = JobShopLoader()
jobs = jobshopLoader.load("data.txt")

